#!/bin/sh

set -e

if [ "$1" = "configure" ] && [ -x /etc/init.d/redapid ]; then
	update-rc.d redapid defaults > /dev/null

	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d redapid start
	else
		/etc/init.d/redapid start
	fi
fi

exit 0
