#!/bin/sh
### BEGIN INIT INFO
# Provides:          redapid
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Start-Before:    brickd
# Short-Description: redapid
# Description:       RED Brick API Daemon
### END INIT INFO

# redapid (RED Brick API Daemon)
# Copyright (C) 2014 Olaf Lüke <olaf@tinkerforge.com>
# Copyright (C) 2014-2015 Matthias Bolte <matthias@tinkerforge.com>
#
# based on skeleton from Debian GNU/Linux
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/redapid
OPTIONS=--daemon
PIDFILE=/var/run/redapid.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting RED Brick API Daemon" "redapid"

	# FIXME: depending on $network does not seem to be enough to ensure that
	# the loopback interface is actually up at this point. just wait 60 seconds
	# here for lo to come up to ensure that scheduled programs can connect via
	# localhost to brickd
	TIMEOUT=60
	RESULT=`ifconfig | grep -e '^lo '`
	while [ $TIMEOUT -gt 0 ] && [ -z "$RESULT" ]; do
		sleep 1
		TIMEOUT=$(($TIMEOUT - 1))
		RESULT=`ifconfig | grep -e '^lo '`
	done

	start_daemon -p $PIDFILE $DAEMON $OPTIONS
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping RED Brick API Daemon" "redapid"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
	;;
  restart|force-reload)
	$0 stop
	sleep 1
	$0 start
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON "redapid" && exit 0 || exit $?
	;;
  *)
	echo "Usage: /etc/init.d/redapid {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
